//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignment
    {
        public int ConsignmentID { get; set; }
        public int BrokerID { get; set; }
        public int BrokerageCompanyID { get; set; }
        public int ProductID { get; set; }
        public int QuantityOfUnits { get; set; }
        public string DeliveryCondition { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
    
        public virtual Broker Broker { get; set; }
        public virtual BrokerageCompany BrokerageCompany { get; set; }
        public virtual Product Product { get; set; }
    }
}
