//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HWEntities : DbContext
    {
        public HWEntities()
            : base("name=HWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Broker> Broker { get; set; }
        public virtual DbSet<BrokerageCompany> BrokerageCompany { get; set; }
        public virtual DbSet<Consignment> Consignment { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    }
}
