//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Consignment = new HashSet<Consignment>();
        }
    
        public int ProductID { get; set; }
        public int FirmID { get; set; }
        public string ProductName { get; set; }
        public int GuaranteePeriod { get; set; }
        public string Unit { get; set; }
        public int Price { get; set; }
        public System.DateTime DateManufacture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consignment> Consignment { get; set; }
        public virtual Firm Firm { get; set; }
    }
}
